version: "3"

services:
  proxy:
    image: ${IMAGE_NAME_PREFIX:-socialcomputing/}coursemapper-webserver-proxy${IMAGE_TAG:-latest}
    build: proxy
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - webapp
      - webserver

  webapp:
    image: ${IMAGE_NAME_PREFIX:-socialcomputing/}coursemapper-webserver-webapp${IMAGE_TAG:-latest}
    build:
      context: webapp
    environment:
      BASE_URL: http://localhost:8000/api
    depends_on:
      - webserver

  webserver:
    image: ${IMAGE_NAME_PREFIX:-socialcomputing/}coursemapper-webserver-webserver${IMAGE_TAG:-latest}
    build:
      context: webserver
    environment:
      - PORT=8080
      - COOKIE_SECRET=secret
      - JWT_SECRET=secret
      - PASS=adminpassword
      - MONGO_DB=mongodb://mongo:27017/coursemapper
    volumes:
      - webserver-uploads:/app/public/uploads
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      start_period: 2s
      interval: 10s

volumes:
  mongo:
  webserver-uploads:
