apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sc-cmw-dev
namePrefix: sc-
commonAnnotations:
  contact: Ralf Berger <ralf.berger@uni-due.de>
labels:
- includeSelectors: true
  pairs:
    owner: sc
    stage: dev

configMapGenerator:
- name: ingress
  behavior: merge
  literals:
  - host=dev.coursemapper.soco.inko.cloud

secretGenerator:
- name: webserver
  behavior: merge
  env: webserver.env

images:
- name: socialcomputing/coursemapper-webserver-webapp
  newTag: latest
- name: socialcomputing/coursemapper-webserver-webserver
  newTag: latest

resources:
- ../base
